name: Build and Upload Docker Compose Images


on:
  push:
    branches:
      - main
    paths:
      - compose.yaml
  pull_request:
    branches:
      - main
    paths:
      - compose.yaml

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
    - uses: actions/checkout@v3
      run: |
        docker compose build
        docker login ghcr.io -u ruthl7 -p ${{ secrets.GHCR_TOKEN }}
        docker compose push

     